#!/bin/bash

# Validates whether commit message is of a certain format.
# Aborts commit if message is unsatisfactory

commit_standard_regex='^\[[+-=*]\] [a-zA-Z]+-[0-9]+: .+|merge'
error_message="Aborting commit. Please ensure your commit message meets the
               standard requirement. '[+,-,*,=] <ISSUE-ID>: Commit Message'"

if ! grep -iqE "$commit_standard_regex" "$1"; then
    echo "$error_message" >&2
    exit 1
fi
